//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_CMS.DB_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class BL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BL()
        {
            this.MainFiles = new HashSet<MainFile>();
        }
    
        public int BLID { get; set; }
        public string BL_No { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> VesselID { get; set; }
        public Nullable<System.DateTime> BL_Date { get; set; }
        public string File_Status { get; set; }
        public Nullable<System.DateTime> CopyDocsReceivedOn { get; set; }
        public Nullable<System.DateTime> OrignalDocsReceivedOn { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Consignee Consignee { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Vessel Vessel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainFile> MainFiles { get; set; }
    }
}
