//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_CMS.DB_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        public int ContainerID { get; set; }
        public string Container_Name { get; set; }
        public string Container_Weight { get; set; }
        public string FreeDays { get; set; }
        public string IndexNo { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> ContainerSizeID { get; set; }
        public Nullable<int> VesselID { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual ContainerSize ContainerSize { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Package Package { get; set; }
        public virtual Vessel Vessel { get; set; }
    }
}
