//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_CMS.DB_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainFile
    {
        public int MainFileID { get; set; }
        public string MainFile_Name { get; set; }
        public string STI_No { get; set; }
        public string Bill_No { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public Nullable<int> BLID { get; set; }
        public Nullable<int> InsuranceID { get; set; }
        public string FreeDays { get; set; }
        public string DocsReceivedBy { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        public virtual BL BL { get; set; }
        public virtual Insurance Insurance { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
