//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_CMS.DB_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuLink()
        {
            this.UserLinks = new HashSet<UserLink>();
            this.PageRights = new HashSet<PageRight>();
        }
    
        public int MenuLinkID { get; set; }
        public string MenuLinkText { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string PageURL { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLink> UserLinks { get; set; }
        public virtual MenuLink MenuLinks1 { get; set; }
        public virtual MenuLink MenuLink1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageRight> PageRights { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
