//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_CMS.DB_Code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERP_CMSEntities : DbContext
    {
        public ERP_CMSEntities()
            : base("name=ERP_CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<MenuPanel> MenuPanels { get; set; }
        public virtual DbSet<PageRight> PageRights { get; set; }
        public virtual DbSet<UserRight> UserRights { get; set; }
        public virtual DbSet<UserLink> UserLinks { get; set; }
        public virtual DbSet<MenuLink> MenuLinks { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
    
        public virtual ObjectResult<sp_GetPageRightsByUserAndMenuLinkID_Result> sp_GetPageRightsByUserAndMenuLinkID(Nullable<int> userID, Nullable<int> menuLinkID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var menuLinkIDParameter = menuLinkID.HasValue ?
                new ObjectParameter("menuLinkID", menuLinkID) :
                new ObjectParameter("menuLinkID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPageRightsByUserAndMenuLinkID_Result>("sp_GetPageRightsByUserAndMenuLinkID", userIDParameter, menuLinkIDParameter);
        }
    
        public virtual ObjectResult<sp_GetUserAssignedRights_Result> sp_GetUserAssignedRights(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetUserAssignedRights_Result>("sp_GetUserAssignedRights", userIDParameter);
        }
    
        public virtual ObjectResult<sp_GetUserNonAssignedRights_Result> sp_GetUserNonAssignedRights(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetUserNonAssignedRights_Result>("sp_GetUserNonAssignedRights", userIDParameter);
        }
    }
}
