//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_CMS.DB_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageRight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageRight()
        {
            this.UserRights = new HashSet<UserRight>();
        }
    
        public int PageRightID { get; set; }
        public string Title { get; set; }
        public Nullable<int> MenuLinkID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRight> UserRights { get; set; }
        public virtual MenuLink MenuLink { get; set; }
    }
}
