//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_CMS.DB_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Taxes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Taxes()
        {
            this.Packages = new HashSet<Package>();
        }
    
        public int ProductTaxID { get; set; }
        public string HSCode { get; set; }
        public string CustomDuty { get; set; }
        public string SalesTax { get; set; }
        public string AddSalesTax { get; set; }
        public string IncomeTax { get; set; }
        public string AddCustomDuty { get; set; }
        public string InvoiceFine { get; set; }
        public string IGMD_Blocking { get; set; }
        public string Excise_SindhTax { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
