//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_CMS.DB_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLink
    {
        public int UserLinkID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> MenuLinkID { get; set; }
    
        public virtual User User { get; set; }
        public virtual MenuLink MenuLink { get; set; }
    }
}
