//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_CMS.DB_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRight
    {
        public int UserRightID { get; set; }
        public Nullable<int> PageRightID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual PageRight PageRight { get; set; }
        public virtual User User { get; set; }
    }
}
