//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_CMS.DB_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vessel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vessel()
        {
            this.BLs = new HashSet<BL>();
            this.Containers = new HashSet<Container>();
        }
    
        public int VesselID { get; set; }
        public string Vessel_Name { get; set; }
        public string Code { get; set; }
        public string Vessel_Status { get; set; }
        public string IGM_No { get; set; }
        public Nullable<System.DateTime> IGM_Date { get; set; }
        public Nullable<int> TerminalID { get; set; }
        public string Total_Weight { get; set; }
        public string PortofLoading { get; set; }
        public string PortofDischarge { get; set; }
        public string PlaceofReceipent { get; set; }
        public string PlaceofDelivery { get; set; }
        public Nullable<System.DateTime> Vessel_ArrivalDate { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public Nullable<System.DateTime> FreeDate { get; set; }
        public string GD_No { get; set; }
        public string GD_Date { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BL> BLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Container> Containers { get; set; }
        public virtual Terminal Terminal { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
